### ISSUE TITLE
Crash when GtkFileChooserDialog is called

### ISSUE THREAD

**Issue by tobias47n9e** [tobias47n9e/innsbruck-stereographic#1]
When a button is pressed in the Windows version, that would open the GtkFileChooserDialog the program displays the error:

> (pythonw.exe:2448): GLib-GIO-ERROR **: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'sort-directories-first'

Will take me a while to figure out what is causing this. But it prevents users of the Windows-version to save their figure and parse data from a text-file.

**Comment by tobias47n9e** [comment]
Solution is to run under Windows:

...\gnome> glib-compile-schemas share\glib-2.0\schemas

https://bugzilla.gnome.org/show_bug.cgi?id=746854

**Comment by tobias47n9e** [comment]
Copied the newly compiled files into the `pynsist_pkgs` directory. Repackaged the program and everything works now.

**Comment by takluyver** [comment]
I wonder if it's possible to do the schema compilation without Windows. I'll open a Pynsist issue about this as well.
